version: '2'

services: # Each entry in the service section will create a seperate
  distro:
    image: alpine # image would be downloaded at runtime.
    restart: always # directive used to indicated to restart container if any host issues.
    container_name: Custom_alpine # Container Name
    #entrypoint: tail -f /dev/null

  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ../dump:/tmp/

  web:
    image: nginx
    restart: always
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=sample.com
      - NGINX_PORT=80
    links:
      - database:db
      - distro
